name: Demo-DBB_Build_on_ZOS_With_GitHub_Actions 
## Notes:
#  Runner install: https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners
#  Runner PreReq:  Git, pre-gen'd SSH keys to zOS, network access to zOS,and known_host updated for GH
#  zOS PreReq:     Installed DBB and Git. SSH security and network access to clone the repo 
#  CI pipeline:    Use the simple workflow option to design a new actions yaml file like below
#  DBB Run Mode:   "-impactBuild" (normal mode), "-reset" (clears DBB Meta), "-scanOnly -fullBuild" (baseline)
#  Runner Vars:    add this step to a job to see the env vars "- run: gci env:* | sort-object name"
## 

# Global vars
env:
    # a var with a valid SSH acct on Z. With pre-gen'd and tested keys in the runner. 
    DBB_Host:  'ssh nlopez@tvt6031.svl.ibm.com'    
    
    # scripts on z/OS (SSH user's Home Dir in Unix - USS) 
    Clone:      'All-pipeline-scripts/AzRocketGit-init.sh'
    DBB_Build:  'All-pipeline-scripts/AzDBB-build.sh'
    Publish:    'All-pipeline-scripts/AzPublishUCD.sh'
    
   #?? Job Level vars used to define the project settings           
     MyRepo:      git@github.com:${{ github.repository }}.git
     MyWorkDir:   tmp/ghActions/ghAction-poc-workspace_run_${{ github.run_number }}
     MyWorkSpace: ghAction-poc-workspace    
     MyBranch:    ${{ github.ref }}
                                 
          
    
# "on" trigger to  manually start this workflow. Can add "pull, push..." for auto trigger.   
# see https://docs.github.com/en/actions/learn-github-actions/contexts
on: workflow_dispatch

jobs:    
    Build_on_zOS:    
        runs-on: self-hosted
        steps:       
            - name: Clone  
                - run: ${{ env.DBB_Host  }} ${{ env.Clone }}  ${{ env.MyRepo }}   ${{ env.MyWorkDir }}  ${{ env.MyWorkSpace }}  ${{ env.MyBranch }}
             
            - name: DBB_Impact_Build
                - run: ${{ env.DBB_Host  }} ${{ env.DBB_Build }}   ${{ env.MyWorkDir }}  ${{ env.MyWorkSpace }}  ghAction-poc-app --impactBuild
             
    Test_on_zOS:    
        needs: Build_on_zOS
        runs-on: self-hosted
        steps:
            - name: UnitTest 
                - run: ${{ env.DBB_Host  }} tsocmd submit "'dat.dev.jcl(datdemo2)'" && sleep 10      
             
             