name: Demo-DBB_Build_on_ZOS_With_GitHub_Actions 
# Notes:
#  Runner install: https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners
#  Runner PreReq:  Git, pre-gen'd SSH keys to zOS, network access to zOS,and known_host updated for GH
#  zOS PreReq:     Installed DBB and Git. SSH security and network access to clone the repo 
#  CI pipeline:    Use the simple workflow option to design a new actions yaml file like below
# /* 

# Global vars
env:
    # a var with a valid SSH acct on Z. With pre-gen'd and tested keys in the runner. 
    DBB_Host:  'ssh nlopez@tvt6031.svl.ibm.com'    
    
    # scripts on z/OS (SSH user's Home Dir in Unix - USS) 
    Clone:      'All-pipeline-scripts/AzRocketGit-init.sh'
    DBB_Build:  'All-pipeline-scripts/AzDBB-build.sh'
    Publish:    'All-pipeline-scripts/AzPublishUCD.sh'
    
    MyRepo:      git@github.com:${{ github.repository }}.git
    MyBranch:    ${{ github.head.ref }}
    MyWorkSpace: ghAction_poc-workspace
    MyWorkDir:   tmp/ghActions/ghAction_poc-workspace_${{ github.job }}


# the on trigger is for manually starting the workflow from the runner (agent)
# add repo events like pull, push...  
on: workflow_dispatch

jobs:     
    Build_on_zOS:    
        runs-on: self-hosted        
        steps:
            - run: ${{ env.DBB_Host  }} ${{ env.Clone }}  ${{ env.MyRepo }}   ${{ env.MyWorkDir }}  ${{ env.MyWorkSpace }}  ${{ env.MyBranch }} 
             
