name: Demo-DBB_Build_on_ZOS_With_GitHub_Actions 

# the on trigger is for manually starting the workflow from the runer (agent)
on: workflow_dispatch
jobs:
  Build_to_USS:
    runs-on: self-hosted 
    steps:      
      - run: echo 'clone' ${{GITHUB_ID}}
      - run: echo 'DBB Build'
      - run: echo 'Publish Artifacts'
